[package]
name = "smartwatch"
version = "0.1.0"
edition = "2021"

[dependencies]
btleplug = "0.11.6"
chrono = "0.4.38"
tokio = { version = "1.41.0", features = ["full"] }
pretty_env_logger = "0.5"
uuid = { version = "1", features = ["v4"] }
futures = "0.3"
